### ISSUE TITLE
Max Choices Error is always showing by default

### ISSUE THREAD

**Issue by 0ex-d** [rinxun/custom-questions#3]
**Problem steps**
1. When the question component loads
2. User selects `Single Choice/Multiple Choice`
3. it always shows the error "A maximum of 3 choices can be set!"

**Suggestion**
This should be hidden and only shown when the user tries to add more that MAX_ALLOWED choices.

<img width="477" alt="Screenshot 2021-12-14 at 13 15 24" src="https://user-images.githubusercontent.com/3173957/146005256-26c7359a-151d-419e-aa0e-6e8ee41ddc89.png">
.

**Comment by JandenMa** [comment]
Gotcha, I will polish it. Thanks

**Comment by JandenMa** [comment]
Fixed.
https://github.com/rinxun/custom-questions/releases/tag/1.1.7
