### ISSUE TITLE
Add action buttons to control each question

### ISSUE THREAD

**Issue by 0ex-d** [rinxun/custom-questions#4]
Currently, we can render each questions and choice. It would be great if there is a way to add buttons (e.g delete) so that each question can be deleted.

This is specific to `AnswerGroup` component, I suggest something around passing a prop;

```
<AnswerGroup key={id} actionButtons={...}>
```

<img width="343" alt="Screenshot 2022-01-15 at 02 38 42" src="https://user-images.githubusercontent.com/3173957/149605947-de005737-a1f6-40bf-b806-657d62078a76.png">

**Comment by JandenMa** [comment]
Thanks for your feedback. As an atomic component / reusable library, it couldn't include too many specific actions/scenarios. Please add a wrapper by yourself to handle it.
